### ISSUE TITLE
ex446的题意——回应NOT QUITE UNDERSTAND THIS EXERCISE!!!

### ISSUE THREAD

**Issue by HunterYIboHu** [jiangpengnju/htdp2e#2]
你自己在[源文件](https://github.com/jiangpengnju/htdp2e/blob/master/generative-recursion/algorithms-that-backtrack/ex446.rkt#L410)中写道：`NOT QUITE UNDERSTAND THIS EXERCISE!!!`。这是我写issue的原因。

这题的原题是：

```
Exercise 446. Test find-path. Use the function to find a path from 'A to 'G in
sample-graph. Which one does it find? Why?

Design the function test-on-all-nodes, which consumes a graph g and tries to
find a path find-path between all pairs of nodes in g. If it succeeds, it
produces #true. Test the function on sample-graph. 
```

我的理解是，第一个问题要求我们解释找到的路径是`'(A B E F G)`的原因；第二个问题则要求我们首先找到图中所有节点（不重复）两两组成的元素对（包括顺序不同但元素相同的元素对，比如`(list 'D 'E)`和`(list 'E 'D)`），然后调用函数`find-path`来测试是否每个元素对都存在相应的路径。如果测试失败，则返回`#false`；否则返回`#true`。

**Comment by jiangpengnju** [comment]
@HunterYIboHu 
查了一下最新的stable版本的书稿，现在的题目描述如下：
`Design test-on-all-nodes, a function that consumes a graph g and determines whether there is a path between any pair of nodes.`
原来的描述确实看不懂。
